mysite/myapp/urls.py
from django.urls import path
from myapp.views import index, itemsid, contact

app_name = 'myapp'

urlpatterns = [
    path('index/', index),
    path('index/<int:my_id>/', itemsid, name='detail'),
    path('contact/', contact)

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls', namespace='myapp'))

]

mysite/myapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)


    def __str__(self):
        return self.name

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product


def index(request):
    items = Product.objects.all()
    context = {
        'items':items
    }
    return render(request, 'myapp/index.html', context)


def itemsid(request, my_id):
    item = Product.objects.get(id=my_id)
    context = {
        'item':item
    }
    return render(request, 'myapp/detail.html', context=context)


def contact(request):
    return HttpResponse('<h1> Страница для связи с администратором! </h1>')

mysite/myapp/templates/myapp/detail.html
<h1> 
    This is detail page for: {{item.name}}
</h1>

mysite/myapp/templates/myapp/index.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}"> 
    </head>

    <body class="bg-sky-500">
        <h1>Информация о товарах: </h1>
        {% for item in items %}
        <a href="{% url 'myapp:detail' item.id %}">
        ID: {{item.id}} | Название: {{item.name}} | Цена: {{item.price}} | Описание: {{item.description}} <br>
        </a>
        {% endfor %}
    </body>


</html>